#!/bin/bash
# 
# ██╗     ██╗   ██╗██╗███████╗██████╗ ███████╗    ██████╗ ███████╗██╗   ██╗
# ██║     ██║   ██║██║██╔════╝██╔══██╗██╔════╝    ██╔══██╗██╔════╝██║   ██║
# ██║     ██║   ██║██║███████╗██████╔╝█████╗      ██║  ██║█████╗  ██║   ██║
# ██║     ██║   ██║██║╚════██║██╔═══╝ ██╔══╝      ██║  ██║██╔══╝  ╚██╗ ██╔╝
# ███████╗╚██████╔╝██║███████║██║     ██║         ██████╔╝███████╗ ╚████╔╝ 
# ╚══════╝ ╚═════╝ ╚═╝╚══════╝╚═╝     ╚═╝         ╚═════╝ ╚══════╝  ╚═══╝  
# Email: luispfcanales@gmail.com
# Twitter: @luispfcanales

#swaywm 
sudo pacman -S sway --noconfirm
sudo pacman -S waybar --noconfirm
#screenshot 
sudo pacman -S grim --noconfirm
sudo pacman -S slurp --noconfirm
#brightness 
sudo pacman -S light --noconfirm
#launcher
sudo pacman -S wofi --noconfirm
#screen shared 
sudo pacman -S wayvnc --noconfirm
sudo pacman -S tigervnc --noconfirm
#icons
sudo pacman -S ttf-font-awesome --noconfirm
#dependencies NVIM
sudo pacman -S xdg-utils --noconfirm #live file.md

if [[ -d $HOME/.config ]]; then
	./links.sh
else
	mkdir $HOME/.config
	./links.sh
fi
